//
// This source file is part of the Swift.org open source project
//
// Copyright (c) 2026 Apple Inc. and the Swift project authors
// Licensed under Apache License v2.0 with Runtime Library Exception
//
// See https://swift.org/LICENSE.txt for license information
// See https://swift.org/CONTRIBUTORS.txt for Swift project authors
//

extension Event.Symbol {
  /// A symbol associated with output generated by the testing harness rather
  /// than by tests themselves.
  package static var harness: Self {
    .custom(
      unicodeCharacter: "\u{2699}", // Unicode: GEAR
      windowsCharacter: "\u{2699}", // Unicode: GEAR
      sfSymbolCharacter: "\u{10035F}",
      sfSymbolName: "gear",
      color: .harness
    )
  }
}

extension Color {
  /// A color associated with output generated by the testing harness rather
  /// than by tests themselves.
  package static var harness: Self {
    .rgb(0, 196, 255)
  }
}
