//
// This source file is part of the Swift.org open source project
//
// Copyright (c) 2023 Apple Inc. and the Swift project authors
// Licensed under Apache License v2.0 with Runtime Library Exception
//
// See https://swift.org/LICENSE.txt for license information
// See https://swift.org/CONTRIBUTORS.txt for Swift project authors
//

#if canImport(Synchronization)
private import Synchronization
#endif

/// An ``IssueResponder`` for transforming any issues into known issues.
///
/// Known Issues are issues which are valid and represent broken implementation
/// code, but for whatever reason, the implementation maintainers have
/// deprioritized addressing it.
///
/// Instances of `KnownIssueResponder` are created whenever a
/// ``withKnownIssue(_:isIntermittent:sourceLocation:_:when:matching:)`` call is
/// made. These are added onto the Issue Responder Chain, and then used to mark
/// matching issues as known.
///
/// `KnownIssueResponder` merely records the number of matched issues it
/// encounters, and does not record each individual issue it encounters.
struct KnownIssueResponder: IssueResponder {
  /// The matcher function for this known issue responder.
  let issueMatcher: KnownIssueMatcher

  /// The context to be associated with issues matched by `issueMatcher`.
  let context: Issue.KnownIssueContext

  /// The number of issues this `KnownIssueResponder` and earlier
  /// `KnownIssueResponder`s in the Issue Responder Chain have matched.
  let matchCounter = Allocated(Atomic<Int>(0))

  /// The list of responders in the current issue responder chain before this
  /// responder.
  let previousChain: [any IssueResponder]

  /// Create a new `KnownIssueResponder`
  ///
  /// - Parameters:
  ///   - issueMatcher: The matcher function for this known issue responder.
  ///   - context: The context to be associated with issues matched by
  ///     `issueMatcher`.
  ///   - previousChain: The list of responders in the current issue responder
  ///     chain prior to this responder being added to the issue responder
  ///     chain. Defaults to the current issue responder chain as of when
  ///     this is initialized.
  init(
    issueMatcher: @escaping KnownIssueMatcher,
    context: Issue.KnownIssueContext,
    previousChain: [any IssueResponder] = IssueResponderLink.current?.chain() ?? []
  ) {
    self.issueMatcher = issueMatcher
    self.context = context
    self.previousChain = previousChain
  }

  /// Determins whether the given issues matches this responder or an earlier
  /// `KnownIssuerResponder` in the Issue Responder Chain.
  ///
  /// - Parameter issue: The issue to check for.
  ///
  /// - Returns: Whether the issue matches within the current chain.
  func issueMatchesInChain(_ issue: Issue) -> Bool {
    if issueMatcher(issue) {
      return true
    } else {
      return previousChain.contains {
        ($0 as? KnownIssueResponder)?.issueMatcher(issue) == true
      }
    }
  }

  /// Respond to the given issue by checking if it matches this responder or an
  /// earlier `KnownIssueResponder` in the Issue Responder Chain.
  ///
  /// If the issue matches this responder, then set its `knownIssueContext` to
  /// `context`.
  ///
  /// If the issue matches this or an earlier `KnownIssueResponder`, then also
  /// increment the number of matched issues in this responder.
  ///
  /// - Parameter issue: The issue to handle.
  ///
  /// - Returns: The modified issue if it matches this responder, otherwise the
  ///   given issue.
  func respond(to issue: Issue) -> Issue? {
    var issueCopy = issue
    let matchedIssue: Bool
    if issueMatcher(issue) {
      matchedIssue = true
      if issueCopy.knownIssueContext == nil {
        issueCopy.knownIssueContext = context
      }
    } else {
      matchedIssue = previousChain.contains {
        ($0 as? KnownIssueResponder)?.issueMatcher(issue) == true
      }
    }
    if matchedIssue {
      matchCounter.value.add(1, ordering: .sequentiallyConsistent)
    }
    return issueCopy
  }
}

/// A function that is used to match known issues.
///
/// - Parameters:
///   - issue: The issue to match.
///
/// - Returns: Whether or not `issue` is known to occur.
public typealias KnownIssueMatcher = @Sendable (_ issue: Issue) -> Bool

/// Handle any miscounts by the specified match counter.
///
/// - Parameters:
///   - matchCounter: The counter responsible for tracking the number of matches
///     found by an issue matcher.
///   - comment: An optional comment to apply to any issues generated by this
///     function.
///   - sourceLocation: The source location to which the issue should be
///     attributed.
private func _handleMiscount(
  by matchCounter: Allocated<Atomic<Int>>,
  comment: Comment?,
  sourceLocation: SourceLocation
) {
  if matchCounter.value.load(ordering: .sequentiallyConsistent) == 0 {
    let issue = Issue(
      kind: .knownIssueNotRecorded,
      comments: Array(comment),
      sourceContext: .init(backtrace: nil, sourceLocation: sourceLocation)
    )
    issue.record()
  }
}

// MARK: -

/// Check if an error matches using an issue-matching function, and throw it if
/// it does not.
///
/// - Parameters:
///   - error: The error to test.
///   - scope: The known issue scope that is processing the error.
///   - comment: An optional comment to apply to any issues generated by this
///     function.
///   - sourceLocation: The source location to which the issue should be
///     attributed.
private func _matchError(
  _ error: any Error,
  in responder: KnownIssueResponder,
  comment: Comment?,
  sourceLocation: SourceLocation
) throws {
  // ExpectationFailedError is thrown by expectation checking functions to
  // indicate a condition evaluated to `false`. Those functions record their
  // own issue, so we don't need to create a new issue and attempt to match it.
  if error is ExpectationFailedError {
    return
  }

  let sourceContext = SourceContext(backtrace: Backtrace(forFirstThrowOf: error), sourceLocation: sourceLocation)
  let issue = Issue(
    kind: .errorCaught(error),
    comments: [],
    sourceContext: sourceContext
  )

  if responder.issueMatchesInChain(issue) {
    // It's a known issue and will be marked in the chain.
    issue.record()
  } else {
    // Rethrow the error, allowing the caller to catch it or for it to propagate
    // to the runner to record it as an issue.
    throw error
  }
}

/// Invoke a function that has a known issue that is expected to occur during
/// its execution.
///
/// - Parameters:
///   - comment: An optional comment describing the known issue.
///   - isIntermittent: Whether or not the known issue occurs intermittently. If
///     this argument is `true` and the known issue does not occur, no secondary
///     issue is recorded.
///   - sourceLocation: The source location to which any recorded issues should
///     be attributed.
///   - body: The function to invoke.
///
/// Use this function when a test is known to record one or more issues that
/// should not cause the test to fail. For example:
///
/// ```swift
/// @Test func example() {
///   withKnownIssue {
///     try flakyCall()
///   }
/// }
/// ```
///
/// Because all errors thrown by `body` are caught as known issues, this
/// function is not throwing. If only some errors or issues are known to occur
/// while others should continue to cause test failures, use
/// ``withKnownIssue(_:isIntermittent:sourceLocation:_:when:matching:)``
/// instead.
///
/// ## See Also
///
/// - <doc:known-issues>
public func withKnownIssue(
  _ comment: Comment? = nil,
  isIntermittent: Bool = false,
  sourceLocation: SourceLocation = #Testing::sourceLocation,
  _ body: () throws -> Void
) {
  try? withKnownIssue(comment, isIntermittent: isIntermittent, sourceLocation: sourceLocation, body, matching: { _ in true })
}

/// Invoke a function that has a known issue that is expected to occur during
/// its execution.
///
/// - Parameters:
///   - comment: An optional comment describing the known issue.
///   - isIntermittent: Whether or not the known issue occurs intermittently. If
///     this argument is `true` and the known issue does not occur, no secondary
///     issue is recorded.
///   - sourceLocation: The source location to which any recorded issues should
///     be attributed.
///   - body: The function to invoke.
///   - precondition: A function that determines if issues are known to occur
///     during the execution of `body`. If this function returns `true`,
///     encountered issues that are matched by `issueMatcher` are considered to
///     be known issues; if this function returns `false`, `issueMatcher` is not
///     called and they are treated as unknown.
///   - issueMatcher: A function to invoke when an issue occurs that is used to
///     determine if the issue is known to occur. By default, all issues match.
///
/// - Throws: Whatever is thrown by `body`, unless it is matched by
///   `issueMatcher`.
///
/// Use this function when a test is known to record one or more issues that
/// should not cause the test to fail, or if a precondition affects whether
/// issues are known to occur. For example:
///
/// ```swift
/// @Test func example() throws {
///   try withKnownIssue {
///     try flakyCall()
///   } when: {
///     callsAreFlakyOnThisPlatform()
///   } matching: { issue in
///     issue.error is FileNotFoundError
///   }
/// }
/// ```
///
/// It is not necessary to specify both `precondition` and `issueMatcher` if
/// only one is relevant. If all errors and issues should be considered known
/// issues, use ``withKnownIssue(_:isIntermittent:sourceLocation:_:)``
/// instead.
///
/// - Note: `issueMatcher` may be invoked more than once for the same issue.
///
/// ## See Also
///
/// - <doc:known-issues>
public func withKnownIssue(
  _ comment: Comment? = nil,
  isIntermittent: Bool = false,
  sourceLocation: SourceLocation = #Testing::sourceLocation,
  _ body: () throws -> Void,
  when precondition: () -> Bool = { true },
  matching issueMatcher: @escaping KnownIssueMatcher = { _ in true }
) rethrows {
  guard precondition() else {
    return try body()
  }
  let responder = KnownIssueResponder(
    issueMatcher: issueMatcher,
    context: Issue.KnownIssueContext(
      comment: comment
    )
  )
  defer {
    if !isIntermittent {
      _handleMiscount(
        by: responder.matchCounter,
        comment: comment,
        sourceLocation: sourceLocation)
    }
  }
  try withIssueResponder(responder) {
    do {
      try body()
    } catch {
      try _matchError(error, in: responder, comment: comment, sourceLocation: sourceLocation)
    }
  }
}

/// Invoke a function that has a known issue that is expected to occur during
/// its execution.
///
/// - Parameters:
///   - comment: An optional comment describing the known issue.
///   - isIntermittent: Whether or not the known issue occurs intermittently. If
///     this argument is `true` and the known issue does not occur, no secondary
///     issue is recorded.
///   - isolation: The actor to which `body` is isolated, if any.
///   - sourceLocation: The source location to which any recorded issues should
///     be attributed.
///   - body: The function to invoke.
///
/// Use this function when a test is known to record one or more issues that
/// should not cause the test to fail. For example:
///
/// ```swift
/// @Test func example() {
///   await withKnownIssue {
///     try await flakyCall()
///   }
/// }
/// ```
///
/// Because all errors thrown by `body` are caught as known issues, this
/// function is not throwing. If only some errors or issues are known to occur
/// while others should continue to cause test failures, use
/// ``withKnownIssue(_:isIntermittent:isolation:sourceLocation:_:when:matching:)``
/// instead.
///
/// ## See Also
///
/// - <doc:known-issues>
public func withKnownIssue(
  _ comment: Comment? = nil,
  isIntermittent: Bool = false,
  sourceLocation: SourceLocation = #Testing::sourceLocation,
  _ body: sending @isolated(any) () async throws -> Void
) async {
  try? await withKnownIssue(comment, isIntermittent: isIntermittent, sourceLocation: sourceLocation, body, matching: { _ in true })
}

/// Invoke a function that has a known issue that is expected to occur during
/// its execution.
///
/// - Parameters:
///   - comment: An optional comment describing the known issue.
///   - isIntermittent: Whether or not the known issue occurs intermittently. If
///     this argument is `true` and the known issue does not occur, no secondary
///     issue is recorded.
///   - isolation: The actor to which `body` is isolated, if any.
///   - sourceLocation: The source location to which any recorded issues should
///     be attributed.
///   - body: The function to invoke.
///   - precondition: A function that determines if issues are known to occur
///     during the execution of `body`. If this function returns `true`,
///     encountered issues that are matched by `issueMatcher` are considered to
///     be known issues; if this function returns `false`, `issueMatcher` is not
///     called and they are treated as unknown.
///   - issueMatcher: A function to invoke when an issue occurs that is used to
///     determine if the issue is known to occur. By default, all issues match.
///
/// - Throws: Whatever is thrown by `body`, unless it is matched by
///   `issueMatcher`.
///
/// Use this function when a test is known to record one or more issues that
/// should not cause the test to fail, or if a precondition affects whether
/// issues are known to occur. For example:
///
/// ```swift
/// @Test func example() async throws {
///   try await withKnownIssue {
///     try await flakyCall()
///   } when: {
///     callsAreFlakyOnThisPlatform()
///   } matching: { issue in
///     issue.error is FileNotFoundError
///   }
/// }
/// ```
///
/// It is not necessary to specify both `precondition` and `issueMatcher` if
/// only one is relevant. If all errors and issues should be considered known
/// issues, use ``withKnownIssue(_:isIntermittent:isolation:sourceLocation:_:when:matching:)``
/// instead.
///
/// - Note: `issueMatcher` may be invoked more than once for the same issue.
///
/// ## See Also
///
/// - <doc:known-issues>
public func withKnownIssue(
  _ comment: Comment? = nil,
  isIntermittent: Bool = false,
  sourceLocation: SourceLocation = #Testing::sourceLocation,
  _ body: sending @isolated(any) () async throws -> Void,
  when precondition: () async -> Bool = { true },
  matching issueMatcher: @escaping KnownIssueMatcher = { _ in true }
) async rethrows {
  guard await precondition() else {
    return try await body()
  }
  let responder = KnownIssueResponder(
    issueMatcher: issueMatcher,
    context: Issue.KnownIssueContext(
      comment: comment
    )
  )
  defer {
    if !isIntermittent {
      _handleMiscount(
        by: responder.matchCounter,
        comment: comment,
        sourceLocation: sourceLocation
      )
    }
  }
  try await withIssueResponder(responder) {
    do {
      try await body()
    } catch {
      try _matchError(error, in: responder, comment: comment, sourceLocation: sourceLocation)
    }
  }
}
