# This source file is part of the Swift.org open source project
#
# Copyright (c) 2025 Apple Inc. and the Swift project authors
# Licensed under Apache License v2.0 with Runtime Library Exception
#
# See https://swift.org/LICENSE.txt for license information
# See https://swift.org/CONTRIBUTORS.txt for Swift project authors

name: 🪲 Report a bug
description: >
  Report a deviation from expected or documented behavior.
labels: [bug, triage-needed]
body:
  - type: markdown
    attributes:
      value: >
        This repository hosts the Swift Testing library and its documentation.
        It does _not_ track feedback for Xcode and other closed source Apple
        developer software such as XCTest; please direct that to
        [Feedback Assistant](https://developer.apple.com/bug-reporting) instead.
  - type: textarea
    attributes:
      label: Description
      description: >
        A concise description of what causes the problem, in human language.
        Though not required, it may help us to more accurately triage the issue
        as well as understand a non-trivial test case.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Reproduction
      description: >
        Provide an example, preferably in a Markdown code block, and explain how
        to build or run it to reproduce the problem. If the problem is a poor or
        unexpected diagnostic, fix-it, or other output, please show this output
        as is. For example, paste it from the terminal. Consider reducing the
        example to the smallest amount of code possible — a smaller example is
        easier to reason about and more appealing to contributors.
      value: |
        ```swift

        ```
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected behavior
      description: Describe the behavior you expected.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Environment
      description: >
        Provide details about the environment in which this problem occurs.
        Include the versions of Swift Testing and the Swift toolchain. If you
        suspect the problem might be specific to a particular platform, please
        specify the platform and OS version as well.
      placeholder: |
        Swift Testing version: (shown in `swift test` output)
        $ swift --version
        $ uname -a
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional information
      description: >
        Any complementary information that could help others to work around the
        problem, and us to better understand the problem and its impact. For
        example, a link to a discussion or post that motivated this report.
    validations:
      required: false
