# This source file is part of the Swift.org open source project
#
# Copyright (c) 2025 Apple Inc. and the Swift project authors
# Licensed under Apache License v2.0 with Runtime Library Exception
#
# See https://swift.org/LICENSE.txt for license information
# See https://swift.org/CONTRIBUTORS.txt for Swift project authors

name: 🌟 Request a change
description: >
  Request a feature, API, improvement, or other change.
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: >
        This repository hosts the Swift Testing library and its documentation.
        It does _not_ track feedback for Xcode and other closed source Apple
        developer software such as XCTest; please direct that to
        [Feedback Assistant](https://developer.apple.com/bug-reporting) instead.

        ___

        Swift Testing is guided by a community-driven evolution process.
        Submitting this form is not a guarantee that the request will be
        considered or implemented. If the request implies an addition, removal,
        or change to the features of Swift Testing or its public interfaces,
        please consider socializing it on the
        [Swift forums](https://forums.swift.org/c/related-projects/swift-testing)
        instead. The Swift forums are the preferred space for sharing ideas and
        discussing them with the Swift community.
  - type: textarea
    attributes:
      label: Motivation
      description: >
        Describe the problems that this idea seeks to address. If the problem is
        that some common pattern is currently hard to express, show how one can
        currently get a similar effect and describe its drawbacks. If it's
        completely new functionality that cannot be emulated, motivate why this
        new functionality would help create better Swift tests.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Proposed solution
      description: >
        Describe the proposed solution to the problem. Provide examples and
        describe how they work. Show how this solution is better than current
        workarounds: is it cleaner, safer, or more efficient?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Alternatives considered
      description: >
        Any alternative approaches that were considered, and why the _proposed
        solution_ was chosen instead.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Additional information
      description: >
        Any complementary information that could be valuable to an author of a
        formal proposal, an implementor, or future discussions. For example, a
        link to a discussion or post that motivated this request.
    validations:
      required: false
