# This source file is part of the Swift.org open source project
#
# Copyright (c) 2025 Apple Inc. and the Swift project authors
# Licensed under Apache License v2.0 with Runtime Library Exception
#
# See https://swift.org/LICENSE.txt for license information
# See https://swift.org/CONTRIBUTORS.txt for Swift project authors

name: ⚙️ Track a task
description: >
  Tasks can be used to track internal work, extract individual subtasks from a
  larger issue, or can serve as umbrella issues themselves.
labels: []
body:
  - type: markdown
    attributes:
      value: >
        This repository hosts the Swift Testing library and its documentation.
        It does _not_ track feedback for Xcode and other closed source Apple
        developer software such as XCTest; please direct that to
        [Feedback Assistant](https://developer.apple.com/bug-reporting) instead.
  - type: textarea
    attributes:
      label: Description
      description: >
        A comprehensive description of the task, in human language.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional information
      description: >
        Any complementary information that could be valuable to an implementor.
        For example, a link to a discussion or post that motivated this task.
    validations:
      required: false
