//
// This source file is part of the Swift.org open source project
//
// Copyright (c) 2024 Apple Inc. and the Swift project authors
// Licensed under Apache License v2.0 with Runtime Library Exception
//
// See https://swift.org/LICENSE.txt for license information
// See https://swift.org/CONTRIBUTORS.txt for Swift project authors
//

public import SwiftSyntax
public import SwiftSyntaxMacros

/// A type describing the expansion of the `@__testing` attribute macro.
///
/// Supported uses:
///
/// - `@__testing(semantics: "nomacrowarnings")`: suppress warning diagnostics
///   generated by macros. (The implementation of this use case is held in trust
///   at ``MacroExpansionContext/areWarningsSuppressed``.
///
/// This type is used to implement the `@__testing` attribute macro. Do not use
/// it directly.
public struct PragmaMacro: PeerMacro, Sendable {
  public static func expansion(
    of node: AttributeSyntax,
    providingPeersOf declaration: some DeclSyntaxProtocol,
    in context: some MacroExpansionContext
  ) throws -> [DeclSyntax] {
    return []
  }

  public static var formatMode: FormatMode {
    .disabled
  }
}
